name: Lazarus Build Workflow

defaults:
  run:
    shell: bash

on:

  workflow_call:
    inputs:
      config:
        description: A JSON object containing configuration values
        required: true
        type: string
    outputs:
      win-artefact-path:
        description: Path to the stored artefact folder
        value: ${{ jobs.build-app.outputs.win-artefact-path }}
      lin-artefact-path:
        description: Path to the stored artefact folder
        value: ${{ jobs.build-app.outputs.lin-artefact-path }}
      osx-artefact-path:
        description: Path to the stored artefact folder
        value: ${{ jobs.build-app.outputs.osx-artefact-path }}

jobs:

  build-app:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      _EXE_: ${{
          matrix.os == 'windows-latest' &&
          format('{0}.exe', fromJSON(inputs.config).app-name) ||
          fromJSON(inputs.config).app-name
        }}
      _EXE_TRIPLET_: ${{
          matrix.os == 'windows-latest' &&
          format('{0}-{1}.exe', fromJSON(inputs.config).app-name, matrix.triplet) ||
          format('{0}-{1}', fromJSON(inputs.config).app-name, matrix.triplet)
        }}

    strategy:
      matrix: ${{ fromJSON(inputs.config).matrix }}

    outputs:
      win-artefact-path: ${{ steps.vars.outputs.win-artefact-path }}
      lin-artefact-path: ${{ steps.vars.outputs.lin-artefact-path }}
      osx-artefact-path: ${{ steps.vars.outputs.osx-artefact-path }}

    steps:
      - name: Build env from inputs.config
        run: |
          echo "app-name=${{ fromJSON(inputs.config).app-name }}" >> "$GITHUB_ENV"
          echo "lpi-path=${{ fromJSON(inputs.config).lpi-path }}" >> "$GITHUB_ENV"

#      - name: Checkout Repository
#        uses: actions/checkout@v3
#        with:
#          submodules: true

#      - name: Install Lazarus
#        uses: gcarreno/setup-lazarus@v3.2.7
#        with:
#          lazarus-version: ${{ matrix.lazarus-versions }}
#          with-cache: false

      - name: Print some values
        run: |
          echo Config: ${{ inputs.config }}
          echo App Name: ${{ env.app-name }}
          echo LPI Path: ${{ env.lpi-path }}/${{ env.app-name }}.lpi
          echo Matrix OS: ${{ matrix.os }}
          echo Executable: ${{ env._EXE_ }}
          echo Executable with triplet: ${{ env._EXE_TRIPLET_ }}

      - name: Build outputs
        id: vars
        run: |
          case "${{ matrix.os }}" in
            "windows-latest")
              echo Setting win-artefact-path to ${{ matrix.triplet }}
              echo "win-artefact-path=${{ matrix.triplet }}" >> "$GITHUB_OUTPUT"
            ;;
            "ubuntu-latest")
              echo Setting lin-artefact-path to ${{ matrix.os }}
              echo "lin-artefact-path=${{ matrix.triplet }}" >> "$GITHUB_OUTPUT"
            ;;
            "macos-latest")
              echo Setting osx-artefact-path to ${{ matrix.os }}
              echo "osx-artefact-path=${{ matrix.triplet }}" >> "$GITHUB_OUTPUT"
            ;;
          esac

      - name: Print outputs
        run: |
          echo Win output: ${{ steps.vars.outputs.win-artefact-path }}
          echo Lin output: ${{ steps.vars.outputs.lin-artefact-path }}
          echo OSX output: ${{ steps.vars.outputs.osx-artefact-path }}
