name: Lazarus Build Workflow

defaults:
  run:
    shell: bash

on:

  workflow_call:
    inputs:
      app_name:
        description: Application Name
        required: true
        type: string
      lpi_path:
        description: Path to the *.lpi file
        required: true
        type: string
      triplets:
        description: A JSON object containing the triplets
        required: true
        type: string
    outputs:
      win_artefact_path:
        description: Path to the stored artefact folder
        value: ${{ jobs.build_app.outputs.win_artefact_path }}
      lin_artefact_path:
        description: Path to the stored artefact folder
        value: ${{ jobs.build_app.outputs.lin_artefact_path }}
      osx_artefact_path:
        description: Path to the stored artefact folder
        value: ${{ jobs.build_app.outputs.lin_artefact_path }}

jobs:

  build_app:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      _EXE_: ${{ matrix.os == 'windows-latest' && format('{0}.exe', inputs.app_name) || inputs.app_name }}
      _EXE_TRIPLET_: ${{ matrix.os == 'windows-latest' && format('{0}-{1}.exe', inputs.app_name, matrix.triplet) || format('{0}-{1}', inputs.app_name, matrix.triplet) }}

    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            triplet: ${{ fromJSON(inputs.triplets).lin }}
#          - os: windows-latest
#            triplet: ${{ fromJSON(inputs.triplets).win }}
#          - os: macos-latest
#            triplet: ${{ fromJSON(inputs.triplets).osx }}

    outputs:
      win_artefact_path: ${{ steps.vars.outputs.win_artefact_path }}
      lin_artefact_path: ${{ steps.vars.outputs.lin_artefact_path }}
      osx_artefact_path: ${{ steps.vars.outputs.osx_artefact_path }}

    steps:
      - name: Print some values
        run: |
          echo App Name: ${{ inputs.app_name }}
          echo LPI Path: ${{ inputs.app_name }}
          echo Triplets: ${{ inputs.triplets }}
          echo Matrix OS: ${{ matrix.os }}
          echo Executable: ${{ env._EXE_ }}
          echo Executable with triplet: ${{ env._EXE_TRIPLET_ }}

      - name: Build outputs
        id: vars
        run: |
          case "${{ matrix.os }}" in
            "windows-latest")
              echo Setting win_artefact_path to ${{ matrix.triplet }}
              echo ::set-output name=win_artefact_path::${{ matrix.triplet }}
            ;;
            "ubuntu-latest")
              echo Setting lin_artefact_path to ${{ matrix.triplet }}
              echo ::set-output name=lin_artefact_path::${{ matrix.triplet }}
            ;;
            "macos-latest")
              echo Setting osx_artefact_path to ${{ matrix.triplet }}
              echo ::set-output name=osx_artefact_path::${{ matrix.triplet }}
            ;;
          esac

      - name: Print outputs
        run: |
          echo Win output: ${{ steps.vars.outputs.win_artefact_path }}
          echo Lin output: ${{ steps.vars.outputs.lin_artefact_path }}
          echo OSX output: ${{ steps.vars.outputs.osx_artefact_path }}
