name: Lazarus Build Workflow

on:

  workflow_call:
    inputs:
      app_name:
        description: Application Name
        default:
        required: true
        type: string
      lpi_path:
        description: Path to the *.lpi file
        default:
        required: true
        type: string
      triplets:
        description: A JSON object containing the triplets
        default:
        required: true
        type: string
    outputs:
      artefact_path:
        description: Path to the stored artefact folder
        value: ${{ jobs.build_app.outputs.artefact_path }}

jobs:

  build_app:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      _EXE_: ${{ matrix.os == 'windows-latest' && format('{0}.exe', inputs.app_name) || inputs.app_name }}
      _EXE_TRIPLET_: ${{ matrix.os == 'windows-latest' && format('{0}-{1}.exe', inputs.app_name, matrix.triplet) || format('{0}-{1}', inputs.app_name, matrix.triplet) }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: ${{ fromJSON(inputs.triplets).win }}
          - os: ubuntu-latest
            triplet: ${{ fromJSON(inputs.triplets).lin }}
          - os: macos-latest
            triplet: ${{ fromJSON(inputs.triplets).osx }}

#    outputs:
#      artefact_path: ${{ steps.build_app.outputs }}

    steps:
      - name: Print some values
        run: |
          echo App Name: ${{ inputs.app_name }}
          echo LPI Path: ${{ inputs.app_name }}
          echo Matrix OS: ${{ matrix.os }}
          echo Executable: ${{ env._EXE_ }}
          echo Executable with triplet: ${{ env._EXE_TRIPLET_ }}
          echo Setting artefact_path to ${matrix.triplet}
          echo "artefact_path=${matrix.triplet}" >> "${GITHUB_OUTPUT}"
