name: Lazarus Main Workflow

permissions:
  contents: write

on:

  push:
    branches: [ main ]
    tags: [ "*" ]
    paths-ignore: [ "README.md", "CHANGELOG.md", "release-notes.md" ]

  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build Application
    uses: gcarreno/re-usable-workflows/.github/workflows/build.lazarus.yml@main
    with:
      config: '{
          "app-name": "helloworld",
          "lpi-path": "src",
          "matrix": {
            "os": [
              "ubuntu-latest",
              "windows-latest",
              "macos-latest"
            ],
            "include":[
              {
                "os": "ubuntu-latest",
                "triplet": "x86_64-linux"
              },
              {
                "os": "windows-latest",
                "triplet": "x86_64-win64"
              },
              {
                "os": "macos-latest",
                "triplet": "x86_64-darwin"
              }
            ],
            "lazarus-versions": [
              "stable"
            ]
          }
        }'

    strategy:
      fail-fast: true

  test:
    name: Test Application
    uses: gcarreno/re-usable-workflows/.github/workflows/test.lazarus.yml@main
    with:
      config: '{
          "app-name": "helloworld",
          "lpi-path": "tests",
          "what-tests": "all",
          "output-format": "plain",
          "matrix": {
            "os":[
              "ubuntu-latest",
              "windows-latest",
              "macos-latest"
            ]
          }
        }'

    strategy:
      fail-fast: true

  release:
    name: Create GitHub Release
    uses: gcarreno/re-usable-workflows/.github/workflows/release.lazarus.yml@main
    needs: [ build, test ]
    with:
      config: '{
          "win": "${{ needs.build.outputs.win-artefact-path }}",
          "lin": "${{ needs.build.outputs.lin-artefact-path }}",
          "osx": "${{ needs.build.outputs.osx-artefact-path }}"
        }'

    strategy:
      fail-fast: true

#{
#  "include":[
#    {
#      "project":"foo",
#      "config":"Debug"
#    },
#    {
#      "project":"bar",
#      "config":"Release"
#    }
#  ]
#}
