name: Lazarus Main Workflow

permissions:
  contents: write

defaults:
  run:
    shell: bash

on:

  push:
    branches: [ main ]
    tags: [ "*" ]
    paths-ignore: [ "README.md", "history.md", "release-notes.md" ]

  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build Application
    uses: ./.github/workflows/build.lazarus.yml
    with:
      app_name: MyApp
      lpi_path: src/MyApp.lpi

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x86_64-win64
          - os: ubuntu-latest
            triplet: x86_64-linux
          - os: macos-latest
            triplet: x86_64-darwin

  test:
    name: Test Application
    uses: ./.github/workflows/test.lazarus.yml
    with:
      app_name: MyApp
      lpi_path: tests/MyAppTest.lpi

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
