name: Lazarus Main Workflow

permissions:
  contents: write

on:

  push:
    branches: [ main ]
    tags: [ "*" ]
    paths-ignore: [ "README.md", "CHANGELOG.md", "release-notes.md" ]

  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build Application
    uses: gcarreno/re-usable-workflows/.github/workflows/build.lazarus.yml@main
    with:
      config: '{
          "app-name": "helloworld",
          "lpi-path": "src",
          "os": ["ubuntu-latest"],
          "lazarus-versions": ["stable"],
          "triplets": {
            "ubuntu-latest": "x86_64-lin"
          }
        }'

    strategy:
      fail-fast: true

  test:
    name: Test Application
    uses: gcarreno/re-usable-workflows/.github/workflows/test.lazarus.yml@main
    with:
      config: '{
          "app-name": "helloworld",
          "lpi-path": "tests",
          "os": ["ubuntu-latest"],
          "what-tests": "all",
          "output-format": "plain"
        }'

    strategy:
      fail-fast: true

  release:
    name: Create GitHub Release
    uses: gcarreno/re-usable-workflows/.github/workflows/release.lazarus.yml@main
    needs: [ build, test ]
    with:
      artefacts: '[
          "win": "${{ needs.build.outputs.win-artefact-path }}",
          "lin": "${{ needs.build.outputs.lin-artefact-path }}",
          "osx": "${{ needs.build.outputs.osx-artefact-path }}"
        ]'

    strategy:
      fail-fast: true
