name: Lazarus Main Workflow

permissions:
  contents: write

on:

  push:
    branches: [ main ]
    tags: [ "*" ]
    paths-ignore: [ "README.md", "CHANGELOG.md", "release-notes.md" ]

  pull_request:
    branches: [ $default-branch ]

jobs:

  build:
    name: Build Application
    uses: gcarreno/re-use-workflows/.github/workflows/build.lazarus.yml@main
    with:
      app-name: helloworld
      lpi-path: src
      triplets: '{
          "win": "x86_64-win64",
          "lin": "x86_64-linux",
          "osx": "x86_64-darwin"
        }'
      config: '{
          "app-name": "helloworld",
          "lpi-path": "src",
          "os": ["ubuntu-latest"],
          "lazarus-versions": ["stable"],
          "triplets": [
            "ubuntu-latest": "x86_64-lin"
          ]
        }'

    strategy:
      fail-fast: true

  test:
    name: Test Application
    uses: gcarreno/re-use-workflows/.github/workflows/test.lazarus.yml@main
    with:
      app-name: helloworldtest
      lpi_path: tests
      config: '{
          "app-name": "helloworld",
          "lpi-path": "tests",
          "os": ["ubuntu-latest"],
          "what-tests": "all",
          "output-format": "plain"
        }'

    strategy:
      fail-fast: true

  release:
    name: Create GitHub Release
    uses: gcarreno/re-use-workflows/.github/workflows/release.lazarus.yml@main
    needs: [ build, test ]
    with:
      artefacts: '[
          "win": "${{ needs.build.outputs.win_artefact_path }}",
          "lin": "${{ needs.build.outputs.lin_artefact_path }}",
          "osx": "${{ needs.build.outputs.osx_artefact_path }}"
        ]'

    strategy:
      fail-fast: true
