name: Lazarus Main Workflow

permissions:
  contents: write

on:

  push:
    branches: [ $default-branch ]
    tags: [ "*" ]
    paths-ignore: [ "README.md", "CHANGELOG.md", "release-notes.md" ]

  pull_request:
    branches: [ $default-branch ]

jobs:

  build:
    name: Build Application
    uses: gcarreno/re-use-workflows/.github/workflows/build.lazarus.yml@$default-branch
    with:
      app_name: MyApp
      lpi_path: src/MyApp.lpi
      triplets: '{
          "win": "x86_64-win64",
          "lin": "x86_64-linux",
          "osx": "x86_64-darwin"
        }'

    strategy:
      fail-fast: true

  test:
    name: Test Application
    uses: gcarreno/re-use-workflows/.github/workflows/test.lazarus.yml@$default-branch
    with:
      app_name: MyApp
      lpi_path: tests/MyAppTest.lpi

    strategy:
      fail-fast: true

  release:
    name: Create GitHub Release
    uses: gcarreno/re-use-workflows/.github/workflows/release.lazarus.yml@latest
    needs: [ build, test ]
    with:
      artefacts: '[
          "win": "${{ needs.build.outputs.win_artefact_path }}",
          "lin": "${{ needs.build.outputs.lin_artefact_path }}",
          "osx": "${{ needs.build.outputs.osx_artefact_path }}"
        ]'

    strategy:
      fail-fast: true
