name: Lazarus Release Workflow

defaults:
  run:
    shell: bash

on:

  workflow_call:
    inputs:
      config:
        description: A JSON object containing configuration values
        required: true
        type: string

jobs:

  release-app:
    name: release
    runs-on: ubuntu-latest

    steps:
      - name: Build env from inputs.config
        run: echo "cfg=${{ fromJSON(inputs.config) }}" >> "$GITHUB_ENV"

      - name: Print some values
        run: |
          echo Config: ${{ inputs.config }}
          echo Win: ${{ env.win }}
          echo Lin: ${{ env.lin }}
          echo OSX: ${{ env.osx }}
