name: Lazarus Release Workflow

defaults:
  run:
    shell: bash

on:

  workflow_call:
    inputs:
      config:
        description: A JSON object containing configuration values
        required: true
        type: string

jobs:

  release-app:
    name: release
    runs-on: ubuntu-latest

    steps:
      - name: Build env from inputs.config
        run: |
          echo "app-name=${{ fromJSON(inputs.config).app-name }}" >> "$GITHUB_ENV"
          echo "tag=${{ fromJSON(inputs.config).tag }}" >> "$GITHUB_ENV"
          echo "win=${{ fromJSON(inputs.config).win }}" >> "$GITHUB_ENV"
          echo "lin=${{ fromJSON(inputs.config).lin }}" >> "$GITHUB_ENV"
          echo "osx=${{ fromJSON(inputs.config).osx }}" >> "$GITHUB_ENV"

      - name: Print some values
        run: |
          echo Config: ${{ inputs.config }}
          echo Tag: ${{ env.tag }}
          echo GitHub Ref: ${{ github.ref }}
          echo GitHub Ref Name: ${{ github.ref_name }}
          echo GitHub Ref Type: ${{ github.ref_type }}
          echo GitHub Event Name: ${{ github.event_name }}
          echo GitHub Event Path: ${{ github.event_path }}
          echo Tag: ${{ env.tag }}
          echo Win Bin: ${{ env.win }}/${{ env.app-name }}.exe
          echo Lin Bin: ${{ env.lin }}/${{ env.app-name }}
          echo OSX Bin: ${{ env.osx }}/${{ env.app-name }}
          echo zip win: ../${{ env.win }}-${{ env.tag }}.zip
          echo tgz lin: ../${{ env.lin }}-${{ env.tag }}.tgz
          echo tgz osx: ../${{ env.osx }}-${{ env.tag }}.tgz
