name: Lazarus Test Workflow

defaults:
  run:
    shell: bash

on:

  workflow_call:
    inputs:
      app_name:
        description: Application Name
        required: true
        type: string
      lpi_path:
        description: Path to the "*.lpi" file
        required: true
        type: string

jobs:

  test_app:
    name: test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      _EXE_: ${{ matrix.os == 'windows-latest' && format('{0}.exe', inputs.app_name) || inputs.app_name }}

    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]

    steps:
      - name: Print some values
        run: |
          echo App Name: ${{ inputs.app_name }}
          echo LPI Path: ${{ inputs.lpi_path }}
          echo Matrix OS: ${{ matrix.os }}
          echo Executable: ${{ env._EXE_ }}
