name: Lazarus Test Workflow

defaults:
  run:
    shell: bash

on:

  workflow_call:
    inputs:
      app-name:
        description: Application Name
        required: true
        type: string
      lpi-path:
        description: Path to the "*.lpi" file
        required: true
        type: string
      config:
        description: A JSON object containing configuration values
        required: true
        type: string

jobs:

  test-app:
    name: test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      _EXE_: ${{
          matrix.os == 'windows-latest' &&
          format('{0}.exe', fromJSON(inputs.config).app-name) ||
          fromJSON(inputs.config).app-name
        }}

    strategy:
      matrix:
        #os: [ubuntu-latest, macos-latest, windows-latest]
        #os: [ubuntu-latest]
        os: ${{ fromJSON(inputs.config).os }}

    steps:
      - name: Print some values
        run: |
          echo App Name: ${{ inputs.app-name }}
          echo LPI Path: ${{ inputs.lpi-path }}/${{ inputs.app-name }}.lpi
          echo Matrix OS: ${{ matrix.os }}
          echo Executable: ${{ env._EXE_ }}
          echo Config: ${{ inputs.config }}
