name: Lazarus Test Workflow

defaults:
  run:
    shell: bash

on:

  workflow_call:
    inputs:
      config:
        description: A JSON object containing configuration values
        required: true
        type: string

jobs:

  test-app:
    name: test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      _EXE_: ${{
          matrix.os == 'windows-latest' &&
          format('{0}.exe', fromJSON(inputs.config).app-name) ||
          fromJSON(inputs.config).app-name
        }}

    strategy:
      matrix: ${{ fromJSON(inputs.config).matrix }}

    steps:
      - name: Build env from inputs.config
        run: |
          echo "app-name=${{ fromJSON(inputs.config).app-name }}" >> "$GITHUB_ENV"
          echo "lpi-path=${{ fromJSON(inputs.config).lpi-path }}" >> "$GITHUB_ENV"
          echo "what-tests=${{ fromJSON(inputs.config).what-tests }}" >> "$GITHUB_ENV"
          echo "output-format=${{ fromJSON(inputs.config).output-format }}" >> "$GITHUB_ENV"

      - name: Print some values
        run: |
          echo Config: ${{ inputs.config }}
          echo App Name: ${{ env.app-name }}
          echo LPI Path: ${{ env.lpi-path }}/${{ env.app-name }}.lpi
          echo What tests: ${{ env.what-tests }}
          echo Output format: ${{ env.output-format }}
          echo Matrix OS: ${{ matrix.os }}
          echo Executable: ${{ env._EXE_ }}
