name: Lazarus Test Workflow

defaults:
  run:
    shell: bash

on:

  workflow_call:
    inputs:
      config:
        description: A JSON object containing configuration values
        required: true
        type: string

jobs:

  test-app:
    name: test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      _EXE_: ${{
          matrix.os == 'windows-latest' &&
          format('{0}.exe', fromJSON(inputs.config).app-name) ||
          fromJSON(inputs.config).app-name
        }}

    strategy:
      matrix: ${{ fromJSON(inputs.config).matrix }}

    steps:
      - name: Print some values
        run: |
          echo App Name: ${{ fromJSON(inputs.config).app-name }}
          echo LPI Path: ${{ fromJSON(inputs.config).lpi-path }}/${{ fromJSON(inputs.config).app-name }}.lpi
          echo Matrix OS: ${{ matrix.os }}
          echo Executable: ${{ env._EXE_ }}
          echo Config: ${{ inputs.config }}
